// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadLabN1.Entities;

namespace PadLabN1.Migrations
{
    [DbContext(typeof(PadLabN1DbContext))]
    [Migration("20190925092802_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PadLabN1.Entities.Sub", b =>
                {
                    b.Property<int>("SubId");

                    b.Property<int>("SubOnId");

                    b.HasKey("SubId", "SubOnId");

                    b.HasIndex("SubOnId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PadLabN1.Helpers.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PadLabN1.Helpers.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PadLabN1.Entities.Sub", b =>
                {
                    b.HasOne("PadLabN1.Helpers.User", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PadLabN1.Helpers.User", "SubOn")
                        .WithMany("Sub")
                        .HasForeignKey("SubOnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PadLabN1.Helpers.Post", b =>
                {
                    b.HasOne("PadLabN1.Helpers.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
